### PR TITLE
"framework/elements" folder translations for Spanish.

### PR DESCRIPTION
**Pull request by romero350**
Hello!

This is the "framework/elements" folder translations for Spanish. I double-checked them sothey should be ready to be merged.

### CODE REVIEW

**Comment by romero350** [comment]
All the frameworks/elements JSON files have been translated to Spanish. I will wait for the merge before moving to interfaces folder.

Thank you!

**Comment by paperscissors** [comment]
Worth mentioning that I do have some changes coming over from staging that add some more content in some of these files, I can let you know when I do that merge though, if you're interested.

We're all very excited about this!

**Comment by romero350** [comment]
Sure! That would be great. Tell me when you need to update the translation in this folder. I will continue on the interface tomorrow morning :)

**Comment by paperscissors** [comment]
How about onnce you've completed the translations, I'll merge this into the branch I've got the changes in, and then we can review and see what needs to be done?

I believe 90% is in the subscriptions element.

**Comment by romero350** [comment]
Sure! I will try to finish them this week :) Then I can take a look on the merged branch to see the updates needed!

**Pull request merged**
