### PR TITLE
Cashmusicplatform translation cn

### PR DESCRIPTION
**Pull request by susanli3769**
Hi there, 

I have translated more sub folders in text folder, pls review and approve. thanks and best

Susan

### CODE REVIEW

**Comment by susanli3769** [comment]
hi there, 

sorry that I didn't check this until now. Not sure how I can resolve the conflicts? My local file didn't have the duplicated English version and have Chinese only. I tried to delete the English one by clicking on resolve conflicts, but after I closed it, the change can't be saved. Any help or guidance would be much appreciated. 

thanks and best
Susan

**Comment by susanli3769** [comment]
hi there, 

sorry me again. In the interface/admin/components/text folder, I created a separate folder as CN and did translation in there when I started to translate the text folder. But in the same text folder, there is EN & IS folder too. Am wondering whether I shouldn't have had duplicated a CN sub folder and should have just changed IS to CN and translate in there? Am not sure if this is why we are now seeing conflicts? Sorry am new to Git and isn't very sure if what I did is right. Not sure how other people do? Do you mind to offer some insights?  

Thanks and best 
Susan

**Comment by susanli3769** [comment]
hi there, 

Hope all is well. Wondering when this can be merged? Without it being merged, I can't submit more pull request. thanks and best

Susan

**Comment by paperscissors** [comment]
Hey Susan, thanks for the reminder --- been a busy week. All set, thank you!

**Comment by susanli3769** [comment]
Thank you! Have a good one. Best, Susan

Sent from my iPhone

On Feb 19, 2018, at 6:43 PM, paperscissors <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Susan, thanks for the reminder --- been a busy week. All set, thank you!

**Pull request merged**
