### PR TITLE
Turkish Translation 4

### PR DESCRIPTION
**Pull request by mugurcagdas**
Hello,
I translated this project help files from EN to TUR.
I will continue to translate as JSON files.
Could you please check it and approve?
Thanks in advance.

### CODE REVIEW

**Comment by mugurcagdas** [comment]
Proofread, there is no fault in translations.
You can see my previous translations to this project below;
#1275 
#1256 
#1255 
Kindly waiting your answers.

**Comment by mugurcagdas** [comment]
Hello @paperscissors 
Thanks for your previous cooperation.
Waiting for merge as soon as possible.
Regards,

**Comment by fmimza** [comment]
selam. çevireceğin yerleri söyleyebilir misin? aynı yerleri çevirmeyelim.

**Comment by mugurcagdas** [comment]
Hey @paperscissors 
I know you are busy, you explain that before but i am still waiting for your action.
Kindly waiting your answer.
Regards,

**Pull request merged**
