### PR TITLE
Cashmusicplatform translation cn

### PR DESCRIPTION
**Pull request by susanli3769**
Hi there, 

I completed Chinese translation of all app.json files in framework/element and also interface/adm /component/interface. Pls help to review and approve. 

Pls also advise if there is any other files that you'd like me to translation? thanks, 

Best
Susan

### CODE REVIEW

**Comment by paperscissors** [comment]
Thanks, @susanli3769!

It looks like maybe there are a bunch of Markdown and JSON files still in `interfaces/admin/components/text` that still need translation, is that correct?

Thanks!
Tom

**Comment by susanli3769** [comment]
Thanks, Tom. I found them. But strange thing is after I successfully pushed them. I can’t find the compare & pull request in Github. It makes me unable to submit the pull request. Any chance that you can help to look into it? Thanks and best, Susan

Sent from my iPhone

On Feb 12, 2018, at 2:21 PM, paperscissors <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, @susanli3769<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsusanli3769&data=02%7C01%7C%7C21d4a223e20e4c3745c808d5724dd538%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636540600962214322&sdata=uMwybjQ1NpuwFb9mQp0UYO1PL%2BdGMAq32XKRfmoX1U4%3D&reserved=0>!

It looks like maybe there are a bunch of Markdown and JSON files still in interfaces/admin/components/text that still need translation, is that correct?

Thanks!
Tom

**Comment by paperscissors** [comment]
I think it's actually just this one we're commenting on. You might not be seeing it because it's been merged and closed?

You can also see them in the `chinese-simplified-translation` branch: https://github.com/cashmusic/platform/commits/chinese-simplified-translation

**Comment by mugurcagdas** [comment]
Out of topic,
May I ask, why do you stop review my pull requests?
Thanks for your reply sir.

**Comment by susanli3769** [comment]
no, it' s not the same. The one was merged was the interface in interface/admin/component/interface. The one that I pushed and couldn't find is in the text folder... Not sure what happened. If you also can't figure out, I will try to delete my current one and clone a new one to start over, but not sure if that's going to affect all the previous work i've done? thanks,

**Comment by paperscissors** [comment]
@susanli3769 I'm honestly not sure how the utopian.io system works. I've got all your pull requests to date folded into that branch. If for some reason they're not in there, as long as you're doing local commits on your local folder, there should be a history of local commits you can look at there.

**Comment by susanli3769** [comment]
thanks for your quick response. yes, i have the local commits on my local folder. Am also not very sure how utopian.io works in this as they always ask for successful pull proof. I may go to Discord and chat with them on this. Thanks for your support. Best, Susan

**Comment by paperscissors** [comment]
good idea! thanks much!

**Pull request merged**
