### PR TITLE
Turkish Translation 3

### PR DESCRIPTION
**Pull request by cgdgsg22**
Hello,
I translated this project help files from EN to TUR.
I will continue to translate as part4.
Could you please check it and approve?
Thanks in advance.

### CODE REVIEW

**Comment by mugurcagdas** [comment]
Kindly waiting your answer :)
Thanks

**Comment by mugurcagdas** [comment]
Hey,
@paperscissors I am sorry for disturb you but, I am waiting for approval after that I can continue to translate. 
Best Regards,
Mugur Cagdas

**Comment by mugurcagdas** [comment]
Hello @paperscissors 
.json files are also ready. Waiting for your approval.

**Comment by cgdgsg22** [comment]
xx

**Comment by paperscissors** [comment]
hey @mugurcagdas, sorry --- i'm completely inundated with these pull request, and i'm mostly a volunteer at the moment. i thought i had responded, having a hard time keeping track!

very much appreciate these translations. forgive me if i've mentioned it already but there are guidelines here if you need them: https://github.com/cashmusic/platform/wiki/CASH-Platform-Translations

best,
tom

**Pull request merged**
